### ISSUE TITLE
Pytorch 0.4.0

### ISSUE THREAD

**Issue by hello1910** [ku2482/sac-discrete.pytorch#1]
Thanks for this great repo! Would the code also work on Pytorch 0.4.0, other than the Tensorboard-related things? It appears to be the case, just wanted to check.

**Comment by toshikwa** [comment]
Hi, @hello1910.

> Would the code also work on Pytorch 0.4.0, other than the Tensorboard-related things?

I think so. 

If you want to use `torch==0.4`, please just modify importing in `core/trainer.py`.

`torch==1.0`-> `from torch.utils.tensorboard import SummaryWriter`
`torch==0.4`-> `from tensorboardX import SummaryWriter`
