### ISSUE TITLE
Is this line redundant?

### ISSUE THREAD

**Issue by AlexTo** [ku2482/sac-discrete.pytorch#11]
This line seems redundant because we overwrite value of q in the next line anyway ?

https://github.com/ku2482/sac-discrete.pytorch/blob/master/sacd/agent/sacd.py#L118

```
with torch.no_grad():
            # Q for every actions to calculate expectations of Q.
            q1, q2 = self.online_critic(states)
            q = torch.min(q1, q2) # <-- do we need this?
```

**Comment by toshikwa** [comment]
Hi @AlexTo 

Yes. It's redundant.
Sorry about that.

Thank you for sharing :)

**Comment by AlexTo** [comment]
no worries :)
