### ISSUE TITLE
gather methd in calc_current_q function

### ISSUE THREAD

**Issue by ahmadreza9** [ku2482/sac-discrete.pytorch#13]
Hello, @ku2482 
Could you let me know what does gather method do? I would appreciate you for any  example or link which help me to figure out how this function work.
https://github.com/ku2482/sac-discrete.pytorch/blob/cf2295cd4feb6ade249f2c202e86138756cc77d4/sacd/agent/sacd.py#L77

**Comment by toshikwa** [comment]
Hi, @ahmadreza9 
https://pytorch.org/docs/stable/generated/torch.gather.html
