### ISSUE TITLE
Mention in Readme.MD cart pole branch

### ISSUE THREAD

**Issue by VCasecnikovs** [ku2482/sac-discrete.pytorch#18]
Good evening,
In my humble opinion, it would help for users of this repository, if You would mention Your information about tuning target_entropy_ratio. Also, there is interesting information about flat memory.
Best regards,
Vadims.

**Comment by VCasecnikovs** [comment]
For me, it was needed to read all your code and all issues to find out that target_entropy_ratio is tuned parameter, which sometimes it is must-have to tune.

**Comment by toshikwa** [comment]
Thanks for sharing.
I will do it later.
