### ISSUE TITLE
Networks merging

### ISSUE THREAD

**Issue by VCasecnikovs** [ku2482/sac-discrete.pytorch#19]
Why should we have two networks with the same amount of dimensions in input and output, and also with the same logic in output (More percentages in policy network must correlate with bigger q-value in q-network)? In basic SAC it made sense because the q-value was only for the one action which was chosen by actor...  It sounds like unnecessary transfer learning from critique to actor...  So shouldn't we just use q-networks but with the additional parameter of entropy.
Best regards,
Vadims.

**Comment by toshikwa** [comment]
> So shouldn't we just use q-networks but with the additional parameter of entropy.

Actually, you can express the policy as `exp(Q/alpha)` and train only the critic.
This equals Soft Q-learning.

**Comment by VCasecnikovs** [comment]
Unfortunately, I haven't found any comparison on the internet of these 2 methods... Does additional transfer learning help to the model?
