### ISSUE TITLE
difference in core code from p-christ's version

### ISSUE THREAD

**Issue by junhuang-ifast** [ku2482/sac-discrete.pytorch#2]
Hi, im looking at this section of your code (actor loss calculation)  
https://github.com/ku2482/sac-discrete.pytorch/blob/ac02fec3c872f6b25208c080f1ba2e745380e757/code/agent.py#L296

and realised its quite different from this version of the code
https://github.com/p-christ/Deep-Reinforcement-Learning-Algorithms-with-PyTorch/blob/f745a154e9f8ecb6119a86826969f50e57a6e5e7/agents/actor_critic_agents/SAC_Discrete.py#L81

any reason for this ? thanks

**Comment by toshikwa** [comment]
Hi, @junhuang-ifast 

> and realised its quite different from this version of the code

I think both codes calculate actor's loss in the same way.

p-christ's code calculates loss first, then calculates entropies.
However, in fact entropies are calculated while calculating loss, so I explicitly calculate entropies, then calculate loss using entropies.

I hope it helps understanding the algorithm, which maximizes (Q + alpha * entropy).

Anyway, thank you for asking :)

**Comment by junhuang-ifast** [comment]
> p-christ's code calculates loss first, then calculates entropies.
However, in fact entropies are calculated while calculating loss, so I explicitly calculate entropies, then calculate loss using entropies.

wouldn't this lead to different policy loss being calculated? which leads to the network being updated differently.

**Comment by toshikwa** [comment]
Hi, @junhuang-ifast

I carefully read p-christ's code and noticed differences between mine and p-christ's.

- p-christ's calculates loss as : (action_probs * (-Q + log_probs)).mean()
- my code calculates loss as   : (action_probs * (-Q + log_probs)).sum(dim=1).mean()

According to equation (12) of the paper, mine should be correct.
However, results in the paper may be consequences of p-christ's version. (in fact, it's just the difference of the step size.)
So I will test both cases and let you know.

I've never noticed this differences. Thank you for pointing it out :)

**Comment by ahmadreza9** [comment]
Hi, @ku2482
What was your income ?

**Comment by toshikwa** [comment]
@ahmadreza9 
I'm a master's student.

**Comment by ahmadreza9** [comment]
> 
> 
> @ahmadreza9
> I'm a master's student.

That's cool. I found descriptions in https://github.com/ku2482/sac-discrete.pytorch/issues/7.

**Comment by toshikwa** [comment]
I have no idea what you are talking about...

**Comment by ahmadreza9** [comment]
> 
> 
> I have no idea what you are talking about...

I just wanted to know why you used sum for policy loss which you mentioned will test both cases and let @junhuang-ifast know. (I found descriptions in #7.)
