### ISSUE TITLE
Add continue function

### ISSUE THREAD

**Issue by VCasecnikovs** [ku2482/sac-discrete.pytorch#20]
Good evening,
it would be nice to add continue function and some checkpoints, for now I can not measure how hard it would be, but I'll leave and issue here.
Best regards,
Vadim.

**Comment by toshikwa** [comment]
>it would be nice to add continue function and some checkpoints

Could you be more specific?

**Comment by VCasecnikovs** [comment]
As I can see you are saving model to checkpoints. There could happen a situation, when we need to stop training at some time and then continue, but we don't want to start over. So it would be nice to add --continue "folder_with_paths" to train.
