### ISSUE TITLE
Can not gain same values as in code.

### ISSUE THREAD

**Issue by VCasecnikovs** [ku2482/sac-discrete.pytorch#22]
Good evening, 
I have tried to train SAC on PACMAN 2 times with the default config file and also with the slightly changed config file. 
I change the batch size to 2048 and use_per to True. Unfortunately, I didn't get a good policy.
Could You tell me where could be an error and how to solve it? 
Maybe I chose bad params...

![image](https://user-images.githubusercontent.com/29467201/103038268-b7615980-4576-11eb-9b24-9b8d2b6be05e.png)

Best regards,
Vadims.

**Comment by toshikwa** [comment]
> Maybe I chose bad params...

If you think so, why don't you try the default parameters to see what is wrong?

First of all, `batch_size=2048` is too big.
Also, if you modified the code, I can't help you with debugging.

Here are the results of SAC-Discrete in `MsPacmanNoFramsskep-v4` I ran today, and it learned well.

**Default Config**
![スクリーンショット 2020-12-24 13 43 02](https://user-images.githubusercontent.com/37267851/103061493-d4d20a00-45ee-11eb-8302-4736e0faa6d9.png)

**Default Config + use_per=True**
![スクリーンショット 2020-12-24 13 42 49](https://user-images.githubusercontent.com/37267851/103061483-d26fb000-45ee-11eb-96ea-efca01355729.png)

**Comment by VCasecnikovs** [comment]
Good morning,
The red one is the default parameters. 
I'll try to retest with default config again without any changes in code.
Thank you for saying that I should control BS, what is more interesting bigger BS gave me 1200 on the test.
Best regards,
Vadims.

**Comment by VCasecnikovs** [comment]
Good evening,
I have tested with the default settings, all works!
Also, I have tested with my pull request. FloatTensor doesn't lower the performance. Results are the same, but these changes make code more universal.
![image](https://user-images.githubusercontent.com/29467201/103174464-0d7e1780-486b-11eb-8829-47902c191a0b.png)
Hope You will merge it,
Best regards,
Vadims.
