### ISSUE TITLE
Custom heap

### ISSUE THREAD

**Issue by VCasecnikovs** [ku2482/sac-discrete.pytorch#23]
Good evening, 
I'm sorry for so big amount of questions I am asking.
Why do You use the custom heap, instead of heapq, which is in standard library?
https://docs.python.org/3/library/heapq.html
Best regards,
Vadims.

**Comment by toshikwa** [comment]
>Why do You use the custom heap

Where did I use it?
Because I don't remember the code well, could you be more specific?
