### ISSUE TITLE
An issue about training speed

### ISSUE THREAD

**Issue by Hugh-Cai** [ku2482/sac-discrete.pytorch#26]
Hi, Toshiki

I run this code with `cuda` and `cpu` separately, and find the training speed is as the same slow no matter which device. Is this a normal phenomenon or a bug?

Thanks

**Comment by toshikwa** [comment]
Please confirm if your CUDA and PyTorch versions are compatible, as I mentioned the following in README.
>"If you're using other than CUDA 10.2, you may need to install PyTorch for the proper version of CUDA. See [instructions](https://pytorch.org/get-started/locally/) for more details."

**Comment by Hugh-Cai** [comment]
Yes, I use `cuda 11.0` and its corresponding torch version `1.7.1`, but the issue still exists.

**Comment by toshikwa** [comment]
Thanks.

1.
I updated config to reduce the evaluation time.

2.
Could you run the following?
```
import torch
print(torch.cuda.is_available())
a = torch.zeros(4)
a = a.cuda()
print(a.device)
```

3.
Which part of the code takes time? (evaluation or updating?)

**Comment by Hugh-Cai** [comment]
Thanks,

For the above step 2, the console outputs
```python
True
cuda:0
```

And for 3, I have a trial  `from tqdm import trange` and replaced `while` with `for self.steps in trange(1, self.num_steps + 1)` in line 74~78, `base.py`. And the case is as follows:
1. the console outputs about 2it/s no matter  which device during training (while I train Rainbow agent over 70it/s in the same device)
2. I run the default config, and the first evaluation on 'MsPacman' cost about 30s
3. Volatile GPU-Util is about 8%

**Comment by toshikwa** [comment]
>And for 3, I have a trial from tqdm import trange and replaced while with for self.steps in trange(1, self.num_steps + 1) in line 74~78, base.py. And the case is as follows:

This `while` iterates episodes, not steps.

**Comment by Hugh-Cai** [comment]
> This `while` iterates episodes, not steps.

```python
while True:
        self.train_episode()
        if self.steps > self.num_steps:
            break
```
replaced by
```python
for self.steps in trange(1, self.num_steps + 1):
    self.train_episode()
```
and remove `self.steps += 1` in `train.episode()`.

And I only use it to test the training speed.

**Comment by toshikwa** [comment]
So your code runs at 2 episodes per sec, right?

**Comment by Hugh-Cai** [comment]
Sorry, only 2 steps per sec!
Did you test this code in 'cpu' and 'gpu' separately, and is their time cost as the same?

**Comment by toshikwa** [comment]
>Sorry, only 2 steps per sec!

I don't think so. Please read your code carefully

**Comment by Hugh-Cai** [comment]
I'm sorry to disturb you, and I will re-read it carefully. 
Can you tell me how many hours about your running in a `gpu` under the default `config`?
Thanks

**Comment by toshikwa** [comment]
It's fine.
I don't remember, but maybe a couple of hours. (Using `cuda` should be faster)

Actually, currently I don't have any computational resources available for testing. 
Sorry about that.

**Comment by toshikwa** [comment]
Hi, my friend tested it for me, and confirmed that `--cuda` was much faster.

Because the evaluation took too much time by default, I reduced the evaluation steps and interval.
Please `git pull origin master` and try again.

**Comment by Hugh-Cai** [comment]
Thanks for your answer. I also have some doubt about the performance that whether the original paper did some tricks, because I run it in  some `env_id` such as `FreewayNoFrameskip-v4` with the same config and the performance of vanilla agent is not as good as described in the paper.
