### ISSUE TITLE
integration to stable-baselines 3

### ISSUE THREAD

**Issue by lingweizhu** [ku2482/sac-discrete.pytorch#27]
Hi Watanabe-san,

Much appreciation for the user-friendly implementation of discrete SAC.

I have been using stable baselines 3 recently and found that there is no discrete SAC, and I happened to notice that you mentioned in SB3's issue that you could contribute to it. I am wondering have this been done? 

Thanks for your time.

**Comment by toshikwa** [comment]
@lingweizhu 

I wanted to implement it, however sb3 team thought it was a low priority.
If you create a feature request in sb3 repository and mention me there, I will be involved ;)

Thanks!

**Comment by lingweizhu** [comment]
> @lingweizhu
> 
> I wanted to implement it, however sb3 team thought it was a low priority.
> If you create a feature request in sb3 repository and mention me there, I will be involved ;)
> 
> Thanks!

Hi Watanabe-san,

I have created a feature request in SB3 repository and mentioned you and your code base, hope you will have time to check it, many thanks!
