### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by Vildnex** [ku2482/sac-discrete.pytorch#28]
I am not sure how or where but I think there is a memory leak in this code. I've clone de repository and just run it with:

`python train.py --config config/sacd.yaml --env_id MsPacmanNoFrameskip-v4 --cuda --seed 0`

The problem is that after running it for a while is see that my memory is not stoping growing, and it increasing by something like 0.01 GB per few minutes (1-2min usually) in a constant manner. 
Am I missing something?

**Comment by ku2482** [comment]
Hi.
Because the size of ReplayMemory is set to 300000 by default, memory utilization would be growing until 300000 steps.

**Comment by toshikwa** [comment]
Hi @Vildnex 
Sorry, I closed the issue by mistake.

Since the size of the replay memory is set to 300000 by default, the memory usage will increase until the agent reaches 300000 steps. It uses around `300000 * 84 * 84 * 1 byte ~= 2GB`.

How much memory did your training process use?

**Comment by Vildnex** [comment]
I see, so the memory should increase until that 300.000 size is meat. I will put some prints to recheck if the size is going up also after that target is meat but I think it was just my miss understanding.

One question those, if it will be to have another environment with a state of shape 500x20, the way of calculating the memory needed is 300.000 * 500 * 20 * 1 byte ?

**Comment by toshikwa** [comment]
>One question those, if it will be to have another environment with a state of shape 500x20, the way of calculating the memory needed is 300.000 * 500 * 20 * 1 byte ?

It depends on how you implement it.
I used some tricks to reduce memory usage
1. Store images as uint8, not float32
2. Use [LazyFrames](https://github.com/ku2482/sac-discrete.pytorch/blob/master/sacd/env.py#L246) (and load as [here](https://github.com/ku2482/sac-discrete.pytorch/blob/master/sacd/memory/base.py#L99)) when stacking consecutive frames

If you implement it as described above, it would use `300000 * 500 * 20 * 1 byte`.

**Comment by Vildnex** [comment]
Ok, thx so much for responding to me and for the clarifications :). Now I get it, sorry for my miss understanding, I will close this issue now. :D
