### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by Tomeu7** [ku2482/sac-discrete.pytorch#29]
Hello,

I have two questions related to your implementation. 

1. In the update of alpha why is the target entropy not multiplied by action_probs? Something like:

```

entropy_loss = -torch.mean(
            self.log_alpha * ((action_probs * self.target_entropy).sum(dim=1, keepdim=True) - entropies)
            * weights)
```

In the paper, the action probabilities are both multiplied to log_pi and target entropy (equation (11)).

2. A question more related to the paper. How come the target entropy is positive? (-log (1 / |A|)) always gives positive values for A>1. This is strange because in continuous SAC the target entropy is negative.  I found that I was getting negative values for the alpha that is why I am asking.

I tried to use instead (log (1 / |A|)) (and with the modification in point 1) and I still could solve CartPole-v1.

Thanks for your help.

**Comment by toshikwa** [comment]
> In the update of alpha why is the target entropy not multiplied by action_probs? Something like:

`sum (action_probs * constant) = constant`.

>A question more related to the paper. How come the target entropy is positive? (-log (1 / |A|)) always gives positive values for A>1. This is strange because in continuous SAC the target entropy is negative.

Although [the entropy of continuous distributions](https://en.wikipedia.org/wiki/Differential_entropy) can be negative, [that of discrete distributions](https://en.wikipedia.org/wiki/Entropy_(information_theory)) is always positive or 0.

> I found that I was getting negative values for the alpha that is why I am asking.

Did you use my implementation as is?
