### ISSUE TITLE
Miss-understanding math in SAC

### ISSUE THREAD

**Issue by SergeiSovik** [ku2482/sac-discrete.pytorch#9]

**Comment by toshikwa** [comment]
@SergeiSovik 

Hi, is everything okay?

**Comment by SergeiSovik** [comment]
Yes, sorry for blank issue. Everything is ok. Couldnt fully delete it.
Thanks for your great work, it helps me alot with understaning SAC. I wrote my own using Tensorflow 2.2. You can test it here [Google Colab](https://colab.research.google.com/github/SergeiSovik/GSAC/blob/master/sac.en.ipynb)
